version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    environment:
      - CLICKHOUSE_PASSWORD=
    ports:
      - "8123:8123"
      - "9000:9000"
    # environment:
    #   CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    #   CLICKHOUSE_DEFAULT_USER: admin
    #   CLICKHOUSE_DEFAULT_PASSWORD: admin123
    volumes:
      - ./clickhouse/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - app-network

  fluentbit:
    image: fluent/fluent-bit:3.0.4
    container_name: fluentbit
    depends_on:
      - clickhouse
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./fluentbit/extract_resource.lua:/fluent-bit/etc/extract_resource.lua:ro
      - ./logs:/var/log/simulator:ro
      - /var/log/nginx:/var/log/nginx:ro
      - ./remote-nginx-logs:/var/log/remote-nginx
    command:
      ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    networks:
      - app-network

volumes:
  clickhouse_data:

networks:
  app-network:
