[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf


# ── INPUTS ────────────────────────────────────────────────────────────────────

[INPUT]
    Name             tail
    Path             /var/log/nginx/error.log
    Tag              nginx.error
    Parser           nginx_error
    Skip_Long_Lines  On
    Refresh_Interval 5
    Read_from_Head   On
    DB               /var/log/flb-state/nginx_error.db

[INPUT]
    Name             tail
    Path             /var/log/nginx/api-brokers.access.log
    Tag              brokers.access
    Parser           nginx_access
    Skip_Long_Lines  On
    Refresh_Interval 5
    Read_from_Head   On
    DB               /var/log/flb-state/brokers_access.db


# ── FILTERS ───────────────────────────────────────────────────────────────────

[FILTER]
    Name   lua
    Match  brokers.access
    Script /fluent-bit/etc/extract_resource.lua
    Call   extract_resource

[FILTER]
    Name    grep
    Match   brokers.access
    Exclude request_method OPTIONS


# ── OUTPUTS ───────────────────────────────────────────────────────────────────

[OUTPUT]
    Name      http
    Match     nginx.error
    Host      clickhouse
    Port      8123
    URI       /?query=INSERT%20INTO%20estavo.nginx_error_logs%20FORMAT%20JSONEachRow
    Format    json_stream
    Header    Content-Type application/x-ndjson
    http_User default

[OUTPUT]
    Name      http
    Match     brokers.access
    Host      clickhouse
    Port      8123
    URI       /?query=INSERT%20INTO%20estavo.nginx_logs%20FORMAT%20JSONEachRow
    Format    json_stream
    Header    Content-Type application/x-ndjson
    http_User default
